<?xml version="1.0"?>
<package format="2">
  <name>data_monitor</name>
  <version>0.1.0</version>
  <description>Odometry and PCD bird's-eye-view monitoring tools.</description>

  <maintainer email="user@example.com">user</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>rospy</build_depend>
  <build_depend>nav_msgs</build_depend>

  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>nav_msgs</build_export_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>python3-matplotlib</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
  </export>
</package>
